services:
  - type: web
    name: community-connect-backend
    runtime: node
    buildCommand: npm install && npm run build:backend
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false # Set this in Render dashboard
    healthCheckPath: /api/stats
